Description = "Finds potential issues in source code from a Git repository using Semgrep"
Timeout = 7200 # 2 hours
AssetTypes = ["GitRepository"]
RequiredVars = ["GITHUB_ENTERPRISE_ENDPOINT", "GITHUB_ENTERPRISE_TOKEN"]
