Description = "Runs a Nessus scan"
Timeout = 28800 # 8 hour. Expressed in seconds as an integer.
AssetTypes = ["Hostname", "IP", "IPRange"]
RequiredVars = [
  "NESSUS_ENDPOINT",
  "NESSUS_USERNAME",
  "NESSUS_PASSWORD",
  "NESSUS_POLICY_ID",
  "LINKING_KEY"
]
